### ISSUE TITLE
[Bug] From file

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#14]
At the moment I believe the manual indicates that one can input a bunch from a file.
However the file is read in initializeFile(), which is **after** the Lorentz boost. The particles in the file therefore need to be boosted.

I can also add this since I have it on my branch, I just have to be careful how the Lorentz boost is done in the particles

**Comment by aryafallahi** [comment]
I think this issue shall be separated to two issues. First, we need to modify the lorentzboost such that the boosting of parameters are done during the bunch initialization and not initially in the lorentzboost. This issue shall be implemented and tested with ellipsoid. Next, the file initialization can be implemented independently.

**Comment by arnaualba** [comment]
Ok I agree. So you suggest that the boosting of the bunch parameters is done in initializeEllipsoid() instead of doing it in lorentzBoost(), correct? Then initializeFile() would have its own lorentz boosting inside the initializeFile() function.

The alternative would be to have initializeBunch() do create the bunch in the laboratory frame, then right after it add a function bunchLorentzBoost() that boosts all the particles.

**Comment by aryafallahi** [comment]
I agree with the alternative, and as I said previously we should definitely go along that line. But, I would first do it separately so that things are smoothly done. I think in the file input you already do that, because the file input is in lab frame. Once we do this and test the code, I can later copy and paste from your implementation. I just need to be careful with the bunching factor.

**Comment by aryafallahi** [comment]
I would do this implementation step by step, since this implementation affects the other bunch initialization. I mean we should first do this shift between bunch initialization and lorentz-boosting for ellipsoid, then test it with the previous test cases, and then go to the file type.

What I think needs to be done is as follows:

1) Initialization of the ellipsoid should be done with lab frame parameters (here the implementation of initial bunching needs to be carefully considered). For this purpose, a new InitializeEllipsoid function needs to be written let us name it InitializeEllipsoid2 (please do not delete the previous one, jus write the new function in the code and call this function).

2) Then, Lorentz boost does its own work using the already existing gamma and longTrun and any other parameters.

3) The lines concerning the bunch in the lorentzboost needs to be commented.

4) Then, we add a new function that is called after lorentzboost. Let us call it lorentzBoostBunch (we can later rename the first one to lorentzBoostSolver). In this function the boosting of the particles will be done 1 by 1.

5) Finally, we test the implementation with my examples to see if exactly the same results will be delivered.

**Comment by arnaualba** [comment]
I would add 
1.1. move the initializeBunch() function such that it is called before lorentzBoost()

**Comment by arnaualba** [comment]
You can see the new version with
```
git clone https://github.com/arnaualba/mithra.git
git checkout fromFile
```

In this branch I have done the steps that we talked about.

**Comment by arnaualba** [comment]
Some tasks that were done in initializeEllipsoid() are not done in initializeEllipsoidLab(), since lambda and gamma_ are unkown. These are done later in lorentBoostBunch(), when said parameters have been computed.
These tasks are the bunching factor, shot noise, and adding tails for the uniform case.
Let me know if you agree with this approach

**Comment by aryafallahi** [comment]
The new implementation is producing different results. it is not close to the correct result. I caught some mistakes. Let me see if I can fix it I will copy your functions in my branch and work there directly on the master.

**Comment by arnaualba** [comment]
Thanks for fixing it, I did not have time to do any tests with what I had implemented

**Comment by arnaualba** [comment]
> Thanks for fixing it, I did not have time to do any tests with what I had implemented

and I think that the new implementation is very nice. I had the problem that lambda and gamma_ were still unknown at bunch initiallization, but you have solved it really nicely with the separation of functions. The implementation for the initialization from file should be straight forward now

**Comment by aryafallahi** [comment]
no problem Arnau! yes, I think it should now be straightforward. Just note that initialGamma is required for the calculation of lambda. The only solution I thought is that the file is read twice: once for calculating average gamma (you can do it just before the lambda calculation, please do not do it in datainput :-) ) and the second time for bunch initialization. It should not make a big problem, as reading the files are typically fast. I have started testing the new version thoroughly. I also need to change the manual. But, I myself am very happy with the new solution. It gives the possibility to consider very complicated bunches.

BTW, I changed your solution so that the bunch is not saved twice in the code. Sometimes bunches with millions of macro-particles are simulated and saving them twice makes memory problems.

**Comment by aryafallahi** [comment]
I think I can close this issue. I will update the description in the manual later as well.
