### ISSUE TITLE
[Feature request] Save initial profile in lab frame

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#20]
I think this would be useful.
After the bunch initialization in the lab frame, the particle positions and momenta can be stored in a file. 

This will be useful for testing the `initializeFile()` function

**Comment by aryafallahi** [comment]
This may be useful for code development and testing, which can be done manually in the code. But, for the user it is obsolete, because he can define a screen profile at the beginning of the undulator to see the bunch profile before entering the undulator. This is probably what a user needs and is already there.

**Comment by arnaualba** [comment]
Ok I think you are right. We can close this issue
