### ISSUE TITLE
[Enhancement] Ideas to save memory

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#52]
MITHRA simulations can take up a lot of memory. Here are a few things I've noticed that could save up memory.

I have noticed that `gbnm`is not used, there is no need to store the momentum in the previous time-step. 
`rnm` and `rnp` are necessary to compute the current density a the grid-points, but `gbnm` is not. 
It is only used in `screenProfile ()`, but it could be modified to work without it. 
It would save some memory to not store them, since for each particle `gbnm` is a 3-dimensional double.

Each particle also stores its charge as a double. This could also be a global variable `solver.Q_`, or something like that, since all particles have the same charge. This would also save some memory. 

Finally, storing the three time-steps for the fields also uses a lot of memory. By looking at the update function
![Screenshot from 2020-06-28 12-12-18](https://user-images.githubusercontent.com/45881038/85944635-a671bb80-b938-11ea-918a-c9aef7f1ebe5.png)

It looks like one could store simply two time-steps. So for example store `fn` and `fnm1`, and then in the update function store the new value in `fnm1`, since the old value of `fnm1` is no longer necessary. Then we can avoid storing a third time-step `fnp1`. This would save a lot of memory, since FDTD requires so many grid-points, and each has to store the vector and scalar potientials, i.e. 4 doubles. 
I suppose that the reason you might not have done this is that the boundaries, edges, and corners require the `n-1` values of the fields in the neighbouring points.
![Screenshot from 2020-06-28 12-20-29](https://user-images.githubusercontent.com/45881038/85944787-c655af00-b939-11ea-8fa1-75db3003a123.png)

I think we could fix this by doing the boundary updates in 2 steps. Firstly, the `fnm1` components are added to the update equations of the boundaries and corners. Secondly, the non-boundary points are updated. Thirdly, the boundaries are updated by adding the `fn` and `fnm1` (now containing the new updated values) fields.
It is a bit complex and one must be careful to correctly implement it, but it would save a lot of memory

**Comment by aryafallahi** [comment]
Hi Arnau, below I write my inputs to the ideas:

MITHRA simulations can take up a lot of memory. Here are a few things I've noticed that could save up memory.

I have noticed that gbnmis not used, there is no need to store the momentum in the previous time-step.
rnm and rnp are necessary to compute the current density a the grid-points, but gbnm is not.
It is only used in screenProfile (), but it could be modified to work without it.
It would save some memory to not store them, since for each particle gbnm is a 3-dimensional double.

_I think gbnm can be removed. We just need to make sure that in the export of bunch properties it is not exported. But, just removing gbnm will probably not make a large difference in memory usage._

Each particle also stores its charge as a double. This could also be a global variable solver.Q_, or something like that, since all particles have the same charge. This would also save some memory.

_I had before simulations where two bunches with different charges should propagate together. I used then similar number of macro-particles but different charges for each macro-particle. I think in general this needs to be there. In future if we put ions for plasma simulations, we need to use a different Q for the macro-particle as well_

Finally, storing the three time-steps for the fields also uses a lot of memory. By looking at the update function

It looks like one could store simply two time-steps. So for example store fn and fnm1, and then in the update function store the new value in fnm1, since the old value of fnm1 is no longer necessary. Then we can avoid storing a third time-step fnp1. This would save a lot of memory, since FDTD requires so many grid-points, and each has to store the vector and scalar potientials, i.e. 4 doubles.
I suppose that the reason you might not have done this is that the boundaries, edges, and corners require the n-1 values of the fields in the neighbouring points.

_I generally agree with this. I thought because of the boundary problem it is easier to have fields separately at three steps. But, you need to be later also careful with data communication that fnm1 is communicated. In general, I think this is possible. I just do not know what will be the impact on the code speed. Probably nothing, because the boundary part is done in a very small time compared to the volume part._

I think we could fix this by doing the boundary updates in 2 steps. Firstly, the fnm1 components are added to the update equations of the boundaries and corners. Secondly, the non-boundary points are updated. Thirdly, the boundaries are updated by adding the fn and fnm1 (now containing the new updated values) fields.
It is a bit complex and one must be careful to correctly implement it, but it would save a lot of memory

**Comment by arnaualba** [comment]
Ok thank you for the feedback Arya.

When I have time I will experiment a bit with these ideas to see how much memory we can save.
I don't expect a gain in speed, but I do expect less memory usage.

**Comment by arnaualba** [comment]
I think you recently implemented most of these things so this issue can be closed.
